/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GameSchema extends BaseModel {
  static $columns = ['id', 'title', 'description', 'genre', 'platform', 'imageUrl', 'releaseYear', 'createdAt', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column()
  declare genre: string | null
  @column()
  declare platform: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare releaseYear: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
